=== waerks/Interface3XMLExercices/exe01/exe01.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <!-- TYPE SIMPLE -->
    <xsd:simpleType name="T_string_2_16">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="2"/>
            <xsd:maxLength value="16"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="T_string_2_64">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="2"/>
            <xsd:maxLength value="64"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="T_string_date_format">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="4"/>
            <xsd:maxLength value="10"/>
            <xsd:pattern value="([0-9]{4}|[0-9]{2}\/[0-9]{2}\/[0-9]{4})"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="T_attr_date_format">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="yyyy"/>
            <xsd:enumeration value="dd-mm-yyyy"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- TYPE COMPLEXE -->
    <xsd:complexType name="T_livres">
        <xsd:sequence>
            <xsd:element ref="livre" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="T_livre">
        <xsd:sequence>
            <xsd:element ref="titre"/>
            <xsd:element ref="auteur" maxOccurs="unbounded"/>
            <xsd:element ref="genre"/>
            <xsd:element ref="date-publication"/>
        </xsd:sequence>
        <xsd:attribute name="nom-série" type="T_string_2_16"/>
        <xsd:attribute name="tome" type="xsd:positiveInteger"/>
    </xsd:complexType>

    <xsd:complexType name="T_date-publication">
        <xsd:simpleContent>
            <xsd:extension base="T_string_date_format">
                <xsd:attribute name="format" type="T_attr_date_format"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="T_auteur">
        <xsd:all>
            <xsd:element name="prénom"/>
            <xsd:element name="nom"/>
        </xsd:all>
    </xsd:complexType>

    <!-- ELEMENTS -->
    <xsd:element name="livres" type="T_livres"/>
    <xsd:element name="livre" type="T_livre"/>
    <xsd:element name="titre" type="T_string_2_64"/>
    <xsd:element name="auteur"/>
    <xsd:element name="prénom" type="T_string_2_16"/>
    <xsd:element name="nom" type="T_string_2_16"/>
    <xsd:element name="genre" type="T_string_2_16"/>
    <xsd:element name="date-publication" type="T_date-publication"/>
</xsd:schema>

=== waerks/Interface3XMLExercices/exe01/exe01.xml
<?xml version="1.0" encoding="UTF-8"?>
<livres
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="./exe01.xsd">
    <livre nom-série="Harry Potter" tome="1">
        <titre>Harry Potter : A l'école des sorciers</titre>
        <auteur>
            <prénom>J.K.</prénom>
            <nom>Rowling</nom>
        </auteur>
        <genre>Fantasie</genre>
        <date-publication format="dd-mm-yyyy">21/06/1999</date-publication>
    </livre>
    <livre nom-série="Harry Potter" tome="2">
        <titre>Harry Potter : La chambre des secrets</titre>
        <auteur>
            <prénom>J.K.</prénom>
            <nom>Rowling</nom>
        </auteur>
        <genre>Fantasie</genre>
        <date-publication format="dd-mm-yyyy">21/06/2002</date-publication>
    </livre>
    <livre>
        <titre>Jhon : le petit train</titre>
        <auteur>
            <prénom>Samuel</prénom>
            <nom>Legrain</nom>
        </auteur>
        <genre>Enfance</genre>
        <date-publication format="dd-mm-yyyy">20/08/2024</date-publication>
    </livre>
</livres>
